### ISSUE TITLE
Issues with QNAP NAS

### ISSUE THREAD

**Issue by moexizer** [cmj2002/warp-docker#40] opened 2024-12-05 08:05 UTC
Running the latest version on my qnap nas and I got the log

2024-12-05T07:44:10.835Z  INFO firewall::engine: Firewall starting
2024-12-05T07:44:10.838Z  WARN firewall::linux: Failed to run NFT command output=Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }
2024-12-05T07:44:10.838Z  WARN firewall::linux: Failed to set firewall rules via stdin. Retrying using temporary file exit_code=ExitStatus(unix_wait_status(256))
2024-12-05T07:44:10.842Z ERROR firewall::linux: Failed to start firewall with exit code: exit status: 1
2024-12-05T07:44:10.842Z  WARN firewall::engine: fw.apply_config_changes failed e=ApplyError("nft command failed with return code: 256")
2024-12-05T07:44:10.842Z DEBUG firewall::change: Firewall allow API ips api_ips=[162.159.192.1, 2606:4700:d0::a29f:c001]
2024-12-05T07:44:10.842Z DEBUG firewall::change: Changing catch all policy Deny->Deny
2024-12-05T07:44:10.842Z DEBUG firewall::change: Firewall allow managed network endpoints managed_network_endpoints=[]
2024-12-05T07:44:10.842Z  INFO firewall::engine: Firewall starting
2024-12-05T07:44:10.846Z  WARN firewall::linux: Failed to run NFT command output=Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }
2024-12-05T07:44:10.846Z  WARN firewall::linux: Failed to set firewall rules via stdin. Retrying using temporary file exit_code=ExitStatus(unix_wait_status(256))
2024-12-05T07:44:10.849Z ERROR firewall::linux: Failed to start firewall with exit code: exit status: 1
2024-12-05T07:44:10.849Z  WARN firewall::engine: fw.apply_config_changes failed e=ApplyError("nft command failed with return code: 256")
2024-12-05T07:44:10.849Z  WARN main_loop: warp::warp_service: Unable to update firewall on disconnect e=ApplyError("nft command failed with return code: 256")
2024-12-05T07:44:10.849Z DEBUG main_loop: warp::warp_service: Determining disconnected reason from connectivity state net_info=IPv4: [eth0; 10.0.3.13; Ethernet]
DNS servers:
 10.0.3.1:53

 power_state=None disconnect_reason=None
2024-12-05T07:44:10.850Z  WARN main_loop: warp::warp_service: Disconnecting, but reason is unknown
2024-12-05T07:44:10.850Z  WARN main_loop: warp::warp_service: Reconnect on settings change failed error=FirewallUpdateFailed(ApplyError("nft command failed with return code: 256"))

I have no idea what to do with it, there are only few options in the container station and system configurations under /etc are basically not editable

**Comment by cmj2002** [comment] 2024-12-05 08:16
It seems to be a similar issue to #16. If you don't need UDP support, you can refer to [this comment](https://github.com/cmj2002/warp-docker/issues/16#issuecomment-2036012829) to use WARP's proxy mode. Otherwise, you have to run WARP in a fully simulated image (a KVM instance or something like that).

**Comment by cmj2002** [comment] 2024-12-23 03:16
Close as a duplicate of #16.

**Closed by cmj2002** 2024-12-23 03:16 UTC
